// Every user-facing string lives here, keyed flat, one object per locale.
// To add a language: copy the `en` block, translate the values, add the locale
// code to LOCALES in i18n.js. No other code changes required — that's the whole
// point of this file existing on its own.
//
// {placeholders} are substituted at render time via i18n.js#t().

export const STRINGS = {
  en: {
    'app.title': 'The Honest Bond Calculator',
    'app.tagline': 'Buy-to-let vs. Bitcoin — the full 10-year cash-flow picture, your assumptions.',
    'hero.propertyPrice': 'Property price',
    'hero.depositPct': 'Deposit',
    'hero.rentMonthly': 'Expected rent (monthly)',
    'results.reIrr': 'Property IRR',
    'results.btcIrr': 'BTC-path IRR',
    'results.kicker': 'Even if Bitcoin returns 0%, this property needs ≥ {rate} p.a. price growth just to break even after all costs.',
    'results.kickerUndefined': 'This deal cannot break even within the horizon at any realistic growth rate — the monthly shortfall exceeds what price growth can repay.',
    'chart.title': 'Net wealth over time',
    'chart.logScale': 'Log scale',
    'chart.re': 'Property (net wealth)',
    'chart.btc': 'Bitcoin path (net wealth)',
    'chart.btcBand': 'Bear (0%) – Half-of-history (~25%) range',
    'waterfall.title': 'Where every rand of the property leg goes over {years} years',
    'waterfall.interest': 'Bank interest',
    'waterfall.rates': 'Rates & taxes',
    'waterfall.maintenance': 'Maintenance',
    'waterfall.insurance': 'Insurance',
    'waterfall.levies': 'Levies',
    'waterfall.management': 'Management fee',
    'waterfall.incomeTax': 'Income tax on rental',
    'waterfall.agentCommission': 'Agent commission (exit)',
    'waterfall.cgt': 'Capital gains tax (exit)',
    'waterfall.upfrontCosts': 'Upfront transfer & bond costs',
    'drawer.title': 'Assumptions',
    'drawer.subtitle': 'Every default below is visible and yours to change.',
    'drawer.depositPct': 'Deposit %',
    'drawer.bondRate': 'Bond interest rate (p.a.)',
    'drawer.bondTerm': 'Bond term (years)',
    'drawer.rentGrowth': 'Rent growth (p.a.)',
    'drawer.vacancyRate': 'Vacancy rate',
    'drawer.ratesTaxesPct': 'Rates & taxes (% of value p.a.)',
    'drawer.maintenancePct': 'Maintenance (% of value p.a.)',
    'drawer.insurancePct': 'Insurance (% of value p.a.)',
    'drawer.managementFeePct': 'Management fee (% of rent)',
    'drawer.marginalTaxRate': 'Marginal income tax rate',
    'drawer.propertyGrowth': 'Property price growth (p.a.)',
    'drawer.metro': 'Metro (sets default growth)',
    'drawer.sectionalTitle': 'Sectional title (levies apply)',
    'drawer.levyMonthly': 'Monthly levy',
    'drawer.agentCommissionPct': 'Agent commission on exit',
    'drawer.moneyMarketRate': 'Money-market rate (RE surplus)',
    'drawer.btcCagr': 'Bitcoin forward CAGR (p.a.)',
    'drawer.btcPreset.bear': 'Bear (0%)',
    'drawer.btcPreset.gold': 'Gold-like (8%)',
    'drawer.btcPreset.half': 'Half of history (~25%)',
    'drawer.btcExchangeFeePct': 'Exchange fee per buy',
    'drawer.horizonYears': 'Horizon (years)',
    'drawer.realTerms': 'Show in real (CPI-adjusted) terms',
    'drawer.cpiRate': 'Assumed CPI (p.a.)',
    'share.copyLink': 'Copy link',
    'share.copyImage': 'Save results as image',
    'share.copied': 'Link copied',
    'footer.disclaimer': 'This is arithmetic, not advice. Assumptions are yours to change.',
    'footer.dataEffective': 'Data effective',
    'footer.methodology': 'Methodology & FAQ',
    'pricing.asOf': 'BTC/ZAR spot: {price} (as of {date}, {source})',
    'pricing.loading': 'Fetching live BTC/ZAR price…',
    'pricing.stale': 'Live price unavailable — using last known value.',
  },
  af: {
    'app.title': 'Die Eerlike Verbandberekenaar',
    'app.tagline': 'Huur-om-te-verhuur vs. Bitcoin — die volle 10-jaar kontantvloei-prentjie, jou aannames.',
    'hero.propertyPrice': 'Eiendomsprys',
    'hero.depositPct': 'Deposito',
    'hero.rentMonthly': 'Verwagte huur (maandeliks)',
    'results.reIrr': 'Eiendom IIO',
    'results.btcIrr': 'Bitcoin-pad IIO',
    'results.kicker': 'Selfs al lewer Bitcoin 0% op, moet hierdie eiendom ≥ {rate} p.j. prysgroei hê net om gelyk te breek na alle kostes.',
    'results.kickerUndefined': 'Hierdie transaksie kan nie binne die horison gelyk breek by enige realistiese groeikoers nie — die maandelikse tekort oorskry wat prysgroei kan terugbetaal.',
    'chart.title': 'Netto welvaart oor tyd',
    'chart.logScale': 'Log-skaal',
    'chart.re': 'Eiendom (netto welvaart)',
    'chart.btc': 'Bitcoin-pad (netto welvaart)',
    'chart.btcBand': 'Beer (0%) – Helfte-van-geskiedenis (~25%) reeks',
    'waterfall.title': 'Waar elke rand van die eiendomsbeen oor {years} jaar heen gaan',
    'waterfall.interest': 'Bankrente',
    'waterfall.rates': 'Belasting & erf',
    'waterfall.maintenance': 'Onderhoud',
    'waterfall.insurance': 'Versekering',
    'waterfall.levies': 'Heffings',
    'waterfall.management': 'Bestuursfooi',
    'waterfall.incomeTax': 'Inkomstebelasting op huur',
    'waterfall.agentCommission': 'Agentkommissie (verkoop)',
    'waterfall.cgt': 'Kapitaalwinsbelasting (verkoop)',
    'waterfall.upfrontCosts': 'Vooraf-oordrag- en verbandkostes',
    'drawer.title': 'Aannames',
    'drawer.subtitle': 'Elke verstek hieronder is sigbaar en joune om te verander.',
    'drawer.depositPct': 'Deposito %',
    'drawer.bondRate': 'Verbandrentekoers (p.j.)',
    'drawer.bondTerm': 'Verbandtermyn (jare)',
    'drawer.rentGrowth': 'Huurgroei (p.j.)',
    'drawer.vacancyRate': 'Leegstandkoers',
    'drawer.ratesTaxesPct': 'Belasting & erf (% van waarde p.j.)',
    'drawer.maintenancePct': 'Onderhoud (% van waarde p.j.)',
    'drawer.insurancePct': 'Versekering (% van waarde p.j.)',
    'drawer.managementFeePct': 'Bestuursfooi (% van huur)',
    'drawer.marginalTaxRate': 'Marginale inkomstebelastingkoers',
    'drawer.propertyGrowth': 'Eiendomsprysgroei (p.j.)',
    'drawer.metro': 'Metro (stel verstek groei)',
    'drawer.sectionalTitle': 'Deeltitel (heffings van toepassing)',
    'drawer.levyMonthly': 'Maandelikse heffing',
    'drawer.agentCommissionPct': 'Agentkommissie by verkoop',
    'drawer.moneyMarketRate': 'Geldmarkkoers (eiendom-oorskot)',
    'drawer.btcCagr': 'Bitcoin voorwaartse KJGK (p.j.)',
    'drawer.btcPreset.bear': 'Beer (0%)',
    'drawer.btcPreset.gold': 'Goud-agtig (8%)',
    'drawer.btcPreset.half': 'Helfte van geskiedenis (~25%)',
    'drawer.btcExchangeFeePct': 'Ruilfooi per aankoop',
    'drawer.horizonYears': 'Horison (jare)',
    'drawer.realTerms': 'Wys in reële (VPI-aangepaste) terme',
    'drawer.cpiRate': 'Aanvaarde VPI (p.j.)',
    'share.copyLink': 'Kopieer skakel',
    'share.copyImage': 'Stoor resultate as beeld',
    'share.copied': 'Skakel gekopieer',
    'footer.disclaimer': 'Dit is rekenkunde, nie raad nie. Aannames is joune om te verander.',
    'footer.dataEffective': 'Data geldig vanaf',
    'footer.methodology': 'Metodologie & VAQ',
    'pricing.asOf': 'BTC/ZAR kontantprys: {price} (vanaf {date}, {source})',
    'pricing.loading': 'Kry lewende BTC/ZAR-prys…',
    'pricing.stale': 'Lewende prys nie beskikbaar nie — laaste bekende waarde word gebruik.',
  },
};

export const LOCALES = Object.keys(STRINGS);
export const DEFAULT_LOCALE = 'en';
